# Generated by Django 6.0.5 on 2026-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='personnes/')),
                ('statut', models.CharField(choices=[('autorise', 'Autorisé'), ('bloque', 'Bloqué')], default='autorise', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
