# Generated by Django 6.0.5 on 2026-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
